const education = [
  {
    title: "Bachelor of Computer Science",
    place: "University of Wollongong",
    dates: "Jan 2021 - May 2024",
    detail: "Major in Software Engineering and Cybersecurity",
  },
  {
    title: "Masters of Computer Science (Cybersecurity)",
    place: "University of Wollongong",
    dates: "Mar 2025 - Present",
  },
];

const certifications = [
  {
    title: "AWS Academy Cloud Foundations",
    issuer: "AWS Academy",
  },
];

const allWork = [
  {
    title: "Bunkerify",
    slug: "bunkerify",
    category: "Cybersecurity Platform",
    website: "https://www.bunkerify.com",
    techStack: [
      "Next.js",
      "Supabase",
      "Vercel",
      "SendGrid",
      "Tailwind CSS",
      "Web Vulnerability Scanner",
    ],
    points: [
      "Built and deployed Bunkerify on Vercel using Next.js, Supabase (PostgreSQL + auth), and SendGrid for transactional email delivery.",
      "Designed a custom scoring engine from scratch mapping 19 assessment questions to ACSC Essential Eight categories with weighted Maturity Level 0-3 calculations per category.",
      "Implemented automated HTML email reports triggered on assessment completion, delivering personalised risk breakdowns and CTAs.",
      "Integrated Calendly booking workflow to convert assessment completions into consultations.",
      "Deployed a live marketing funnel with a landing page and LinkedIn launch assets to drive inbound leads.",
      "Added a website scan after the Essential Eight assessment. Findings are stored in Supabase and included in the results page and email report.",
      "Implemented an email gate for new users prior to scanning, with direct scan access for returning authenticated users.",
    ],
  },
  {
    title: "Job Application Assistant",
    slug: "job-application-assistant",
    category: "Web App",
    repo: "https://github.com/mobeen786822/job-application-assistant",
    techStack: [
      "Python",
      "Flask",
      "Flask-Session",
      "Supabase",
      "Anthropic API",
      "OpenAI API",
      "GitHub Actions",
    ],
    points: [
      "Built a web app that tailors resumes from job descriptions and exports PDF/HTML.",
      "Implemented OpenAI-powered content tailoring with strict no-fabrication rules.",
      "Added private access via VPN-only deployment (Tailscale) on a cloud VM.",
      "Added UI preview, download actions, and loading feedback.",
      "Built a GitHub Actions CI/CD security pipeline using Bandit, Semgrep, Gitleaks, and pip-audit.",
      "Identified and resolved a medium-severity Bandit finding related to an interface binding vulnerability.",
      "Extended into a multi-user SaaS with Supabase Auth, server-side sessions, and a per-user dashboard tracking generation history",
      "Implemented server-side monthly usage limits (10/month per user) with Supabase RLS-enforced data isolation.",
    ],
  },
  {
    title: "Local LLM Benchmark with Ollama",
    slug: "local-llm-benchmark",
    category: "AI Engineering",
    repo: "https://github.com/mobeen786822/local-llm-benchmark",
    techStack: [
      "Python",
      "Ollama",
      "Llama 3.2",
      "Phi-3 Mini",
      "Gemma 2",
      "Ubuntu",
    ],
    points: [
      "I compared Llama 3.2, Phi-3 Mini and Gemma 2 running offline through Ollama on a CPU-only Ubuntu VM.",
      "I checked whether each model finished the task as well as how good the answer was. Timeouts were an important part of the results.",
      "A Python script ran each model through summarisation, JSON extraction, code generation and multi-step reasoning, giving 12 results across the three models.",
      "In this run, Gemma 2 was fastest at 4.8 tokens per second. Llama 3.2 completed all four tasks. Phi-3 Mini produced the best code but struggled with structured output.",
    ],
  },
  {
    title: "Cyber Content Bot",
    slug: "cyber-content-bot",
    category: "AI Engineering",
    repo: "https://github.com/mobeen786822/cyber-content-bot",
    website: "https://cyber-content-bot-ui.onrender.com",
    techStack: [
      "Python",
      "Flask",
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "Anthropic Claude API",
    ],
    points: [
      "I built a dashboard that gathers cybersecurity news and uses Claude Haiku to draft LinkedIn posts for weekly review. It uses Flask, React and TypeScript.",
      "It fetches the past seven days of high and critical CVEs from NVD, known exploited vulnerabilities from CISA KEV and AI security papers from arXiv. The three sources are fetched concurrently.",
      "Users can choose a professional, conversational or technical tone, then regenerate a draft without fetching the same source data again.",
      "The security checks found six dependency CVEs across Flask, Flask-CORS and Requests, plus a high-severity Bandit B201 finding. I fixed those before continuing.",
    ],
  },
  {
    title: "LLM Security Tester",
    slug: "llm-security-tester",
    category: "AppSec",
    repo: "https://github.com/mobeen786822/-llm-security-tester",
    techStack: [
      "Python",
      "Flask",
      "React",
      "Vite",
      "Tailwind CSS",
      "Ollama",
      "Anthropic API",
    ],
    points: [
      "I built a tool with 15 test cases for prompt injection, jailbreaks, system-prompt extraction, data leaks and role confusion.",
      "In this test set, Llama 3.2 resisted all 15 cases. Claude Haiku had three failures and five partial failures on high-severity cases.",
      "The React and Tailwind dashboard groups results by category and severity. Users can expand the prompts and responses or export a JSON report.",
      "Test cases live in a JSON library, so new cases and categories can be added without changing the app code.",
    ],
  },
  {
    title: "Web Vulnerability Scanner",
    slug: "web-vulnerability-scanner",
    category: "AppSec",
    website: "https://web-vulnerability-scanner-lqy5.onrender.com/",
    techStack: [
      "Python",
      "Flask",
      "React",
      "Vite",
      "Tailwind CSS",
      "GitHub Actions",
    ],
    points: [
      "I built six checks for security headers, SSL/TLS, exposed paths, cookie flags, open redirects and information disclosure. A React dashboard displays the results and exports JSON reports.",
      "The scanner accepts one URL or a batch. Python’s ThreadPoolExecutor runs scans concurrently, with a shared requests.Session for each URL.",
      "Each finding includes a severity, status, supporting detail and a suggested fix.",
      "GitHub Actions runs Bandit, Gitleaks and pip-audit. High-severity findings block the pipeline.",
    ],
  },
  {
    title: "Production Support Incident Console",
    slug: "incident-console",
    category: "Operations Simulation",
    repo: "https://github.com/mobeen786822/Production-Support-Incident-Console",
    website: "https://incident-console-ui.onrender.com/",
    techStack: [
      "React",
      "TypeScript",
      "FastAPI",
      "Python",
      "SQLAlchemy",
      "Docker",
      "JWT",
      "GitHub Actions",
    ],
    points: [
      "Built a web-based incident management console to simulate production support workflows end-to-end.",
      "Implemented incident lifecycle tracking with severity, status transitions, ownership, and event timelines.",
      "Added SLA-aware monitoring with breach indicators to support prioritisation and response quality.",
      "Implemented runbook and root-cause analysis capture to improve incident resolution consistency.",
      "Implemented a full-stack security pipeline across Python (Bandit, pip-audit) and JavaScript (npm audit, Gitleaks).",
      "Discovered and resolved 8 CVEs in backend dependencies through targeted remediation and dependency upgrades.",
      "Replaced python-jose with PyJWT due to an unresolvable vulnerability chain and migrated the authentication implementation.",
      "Resolved a high-severity frontend vulnerability by upgrading affected dependencies.",
    ],
  },
  {
    title: "Golden Hour Pilates Website Redesign",
    slug: "golden-hour-pilates",
    category: "Client Website and Production Launch",
    website: "https://www.goldenhourpilates.com.au",
    techStack: [
      "React",
      "Vite",
      "JavaScript",
      "CSS",
      "Booking integration",
      "Vercel",
      "Accessibility",
      "Local SEO",
    ],
    points: [
      "Audited the existing Squarespace homepage and translated its strong identity into a clearer, conversion-focused customer journey.",
      "Rebuilt and launched the production website as a responsive React application using the studio's official identity, photography, and integrated class schedule.",
      "Strengthened the introductory-offer journey with clearer calls to action, persistent mobile booking access, class discovery, beginner guidance, FAQs, and direct contact actions.",
      "Implemented semantic structure, reduced-motion support, keyboard focus states, local-business metadata, responsive QA, and a production Vercel deployment.",
    ],
  },
  {
    title: "JZ Tech Web Studio",
    slug: "jz-tech",
    category: "Business Website and Brand System",
    website: "https://www.jztech.com.au",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Vercel",
      "GitHub Actions",
      "Accessibility",
      "Technical SEO",
    ],
    points: [
      "Designed and launched a production website for an Australian web studio, translating its brand foundation into a distinctive dark editorial interface.",
      "Structured the customer journey around services, delivery process, maintenance, proof, FAQs, and a direct enquiry path.",
      "Implemented a responsive cinematic hero with poster, mobile, reduced-motion, and data-saving fallbacks.",
      "Built portable brand tokens, automated WCAG contrast checks, semantic metadata, structured data, CI validation, and a production Vercel deployment.",
    ],
  },
  {
    title: "JZ Supports & Maintenance Website",
    slug: "jzsm",
    category: "Multi-page Service Website",
    website: "https://www.jzsm.com.au",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Relume",
      "shadcn/ui",
      "Radix UI",
      "Vercel",
      "Accessibility",
    ],
    points: [
      "Designed and launched a seven-route website for a practical support and home-maintenance provider.",
      "Built distinct service journeys for NDIS supports, injury recovery, cleaning, lawns and maintenance, company information, and enquiries.",
      "Adapted genuine Relume components into an editable local component system using shadcn/Radix foundations and project-specific design tokens.",
      "Implemented accessible navigation, motion safeguards, funding disclaimers, semantic metadata, responsive QA, and production Vercel hosting.",
    ],
  },
  {
    title: "Cancer Awareness Mobile App",
    slug: "cancer-awareness-app",
    category: "Mobile App",
    repoNote: "The repository is private. Source code is available on request.",
    techStack: ["React Native", "TypeScript", "Firebase"],
    points: [
      "I built a cross-platform cancer awareness app with React Native and TypeScript.",
      "Firebase handles authentication, cloud storage and messaging.",
      "The app includes location features, media uploads and navigation between its content sections.",
      "Educational content and reminders help users find and return to awareness information.",
      "I considered how to handle sensitive health-related information when designing the app’s data flows.",
    ],
  },
];

const volunteer = [
  {
    title: "Web Developer (catchadrive.com)",
    org: "Catch a Drive",
    dates: "Nov 2025 - Jan 2026",
    points: [
      "I worked on frontend and backend features for Catch a Drive, including booking pages and user interactions.",
      "I built responsive components for the mobile and desktop layouts.",
      "I connected the interface to APIs for dynamic content and user actions.",
    ],
  },
  {
    title: "Web Developer (Hentley.co)",
    org: "Hentley",
    dates: "Jan 2018 - Mar 2019",
    points: [
      "I built custom storefront components for browsing products and navigating the Hentley shop.",
      "I worked on server-side features for product pages, checkout-related flows and content updates.",
      "I adjusted layouts and styles for mobile, tablet and desktop.",
    ],
  },
];

const skillCategories = [
  {
    name: "Core Engineering",
    items: [
      "React",
      "TypeScript",
      "Vite",
      "Tailwind CSS",
      "React Native",
      "Next.js",
      "JavaScript",
      "Node.js",
      "Flask",
      "FastAPI",
      "Docker",
      "Supabase",
      "SQLAlchemy",
      "Nginx",
      "Firebase",
      "REST API Integration",
      "Jest",
      "React Testing Library",
      "Cybersecurity",
      "Networking",
      "SQL",
      "NoSQL",
      "Python",
      "Java",
      "C++",
    ],
  },
  {
    name: "DevSecOps",
    items: [
      "GitHub Actions",
      "Bandit",
      "Semgrep",
      "Gitleaks",
      "pip-audit",
      "npm audit",
      "SAST",
      "dependency scanning",
      "secrets detection",
    ],
  },
];

const cybersecurityTools = [
  "Kali Linux",
  "Nmap",
  "Metasploit",
  "Wireshark",
  "Burp Suite",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Incident Response",
  "Threat Intelligence",
  "Network Segmentation",
  "Log Analysis",
  "Firewall Configuration",
];

export {
  education,
  certifications,
  allWork,
  volunteer,
  skillCategories,
  cybersecurityTools,
};
